Upgrade guava to 31.0.1-jre
Without this, it will have 31.0.1-android which causes the following exception.

```
Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.expireAfterWrite(Ljava/time/Duration;)Lcom/google/common/cache/CacheBuilder;
	at com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl.<init>(GoogleCloudStorageImpl.java:202)
	at com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl.<init>(GoogleCloudStorageImpl.java:317)
	at com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl.<init>(GoogleCloudStorageImpl.java:278)
	at com.google.cloud.hadoop.gcsio.GoogleCloudStorageFileSystem.<init>(GoogleCloudStorageFileSystem.java:150)
	at io.grpc.gcs.GcsioClient.makeWriteRequest(GcsioClient.java:152)
	at io.grpc.gcs.GcsioClient.startCalls(GcsioClient.java:67)
	at io.grpc.gcs.TestMain.main(TestMain.java:47)
```